apiVersion: v1
kind: Service
metadata:
  name: api
  labels: 
    component: api
spec:
  selector:
    component: api
  type: LoadBalancer  
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP

