apiVersion: v1
kind: Pod
metadata:
  name: 10-node-testcontainers
  labels:
    name: 10-node-testcontainers
spec:
  containers:
  - name: node
    image: demo-registry:5000/10-node-testcontainers-in-k3d:0.1
    command: ["/bin/sh","-c"]
    args: ["dockerize -wait tcp://127.0.0.1:2375 -timeout 30s npm test postgresql-container.test.ts && chown -R $USER_ID:$GROUP_ID /app/report && sleep infinity"]
    env:
      - name: DOCKER_HOST
        value: tcp://127.0.0.1:2375
    volumeMounts:
      - name: psql
        mountPath: /app/report
  - name: dind
    image: docker:23.0.1-dind-alpine3.17
    command: [dockerd-entrypoint.sh]
    securityContext:
           privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
  volumes:
    - name: psql
      hostPath:
        path: /report