replicaCount: 1

springBootApp:
  name: api
  image: demo-registry:5000/spring-boot-app:0.1
  env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: password
    - name: DB_HOST    
      valueFrom: 
        configMapKeyRef: 
          name: postgres-config
          key: DB_HOST    
    - name: DB_PORT    
      valueFrom: 
        configMapKeyRef: 
          name: postgres-config
          key: DB_PORT    
    - name: DB_NAME    
      valueFrom: 
        configMapKeyRef: 
          name: postgres-config
          key: DB_NAME    
    - name: DB_URL
      value: "$(DB_HOST):$(DB_PORT)/$(DB_NAME)"  

postgresql:
  name: postgres-service  
  server:   
    image: postgres:14.5-alpine3.16
    env: 
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_PASSWORD
      - name: POSTGRES_DB  
        valueFrom: 
          configMapKeyRef: 
            name: postgres-config
            key: DB_NAME             
      - name: PGDATA
        valueFrom: 
          configMapKeyRef: 
            name: postgres-config
            key: PGDATA     

pgadmin: 
  enabled: true  
  name: pgadmin
  server:
    image: dpage/pgadmin4:6.14
    env:
      - name: PGADMIN_DEFAULT_EMAIL
        value: pgadmin@pgadmin.com
      - name: PGADMIN_DEFAULT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: pgadmin-password
      - name: PGADMIN_USERNAME
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: username         
    ports:
      - name: pgadmin
        containerPort: 80
        protocol: TCP  

initContainers: 
  name: change-permissions
  server: 
    image: busybox:latest

configmap:
  enabled: true
  name: postgres-config

secret: 
  name: postgres-secret 

service-psql:
  type: ClusterIP
  port: 5432

service-api:
  type: LoadBalancer
  port: 8080  

database:
  host: postgres-service-1
  port: 6432
  name: check-db
  



