apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app3: nginx-3
  template:
    metadata:
      labels:
        app3: nginx-3
    spec:
      containers:
        - name: nginx
          image: nginxdemos/hello