apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app1: nginx-1
  template:
    metadata:
      labels:
        app1: nginx-1
    spec:
      containers:
        - name: nginx
          image: nginxdemos/hello