apiVersion: v1
kind: Pod
metadata:
  name: 08-java-testcontainers
spec:
  containers:
    - name: dind-container
      image: docker:23.0.1-dind-alpine3.17
      command: [dockerd-entrypoint.sh]
      securityContext:
             privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
    - name: testcontainer
      image: demo-registry:5000/08-java-testcontainers-in-k3d:0.1
      command: ["/bin/sh", "-c"]
      args: ["dockerize -wait tcp://127.0.0.1:2375 -timeout 20s gradle test && cp -r /app/examples/redis-backed-cache-testng/build /java/java && chown -R $USER_ID:$GROUP_ID /java/java && sleep infinity"]
      env:
        - name: DOCKER_HOST
          value: tcp://127.0.0.1:2375
        - name: TESTCONTAIENRS_RYUK_DISABLED
          value: "true"
        - name: TESTCONTAINERS_CHECKS_DISABLE
          value: "true"
      volumeMounts: 
        - mountPath: /java
          name: data
  volumes: 
    - name: data
      hostPath: 
        path: /report    
  