apiVersion: v1
kind: Pod
metadata:
  name: 06-init-containers
  labels:
    name: 06-init-containers
spec:
  containers:
    - name: reader
      image: ubuntu:23.10
      command: ["sh", "-c", "cat /data/test.txt && sleep infinity"]
      volumeMounts:
        - name: data
          mountPath: /data
  initContainers:
    - name: writer
      image: ubuntu:23.10
      command: ["sh","-c","echo 'Hello World !!!' > /data/test.txt && pwd"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      emptyDir: {}
