apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata: 
  name: 11-argo-java-testcontainers
spec: 
  entrypoint: java-testcontainers-argo  
  volumes:
    - name: data-info
      hostPath:
        path: /report 
  templates: 
    - name: java-testcontainers-argo  
      container: 
        image: demo-registry:5000/11-java-testcontainers-via-workflows:0.1
        command: ["/bin/sh", "-c"]
        args: ["dockerize -wait tcp://127.0.0.1:2375 -timeout 30s gradle test && cp -r /app/examples/redis-backed-cache-testng/build /java/java && chown -R $USER_ID:$GROUP_ID /java/java && sleep infinity"]
        env:
          - name: DOCKER_HOST
            value: tcp://127.0.0.1:2375
          - name: TESTCONTAIENRS_RYUK_DISABLED 
            value: "true"
          - name: TESTCONTAINERS_CHECKS_DISABLE 
            value: "true" 
        volumeMounts:
          - name: data-info
            mountPath: /java     
      sidecars: 
        - name: dind
          image: docker:23.0.1-dind-alpine3.17
          command: [dockerd-entrypoint.sh]
          securityContext:
                privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          
