apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels: 
    app: {{ .Values.pgadmin.name }}
spec:
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 80
  selector:
    app: {{ .Values.pgadmin.name }}
  type: LoadBalancer
