name: K-02 Hello World Python in K3d
on:
  push:
    paths:
      - './kubernetes/02-hello-world-python-in-k3d/**'
      - '.github/workflows/02-hello-world-python-in-k3d.yml'
env:
  CHECK_POD_STATUS: "Running"
  POD_OUTPUT: "Hello, Anna"
  TASK_FOLDER: "${{ github.workspace }}/kubernetes/02-hello-world-python-in-k3d"
  CUSTOM_IMAGE: "localhost:12345/02-hello-world-python-in-k3d:0.1"
  POD_CONTAINER_NAME: "02-hello-world-python"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1

      - name: Check docker available
        run: docker info

      - name: Check if kubernetes is available
        run: k3d version

      - name: Check if src directory exists
        run: |
          if [ -d ${TASK_FOLDER}/src ]; then
          echo "Directory 'src' exists"
          else 
          echo "Error: Directory 'src' does not exist"
          exit 1
          fi

      - name: Check if manifests folder exists
        run: |
          if [ -d ${TASK_FOLDER}/manifests ]; then
          echo "Directory 'manifests' exists"
          else 
          echo "Error: manifests does not exist"
          exit 1
          fi

      - name: Check if src directory contains Dockerfile and .py
        run: |
          if [ -f ${TASK_FOLDER}/src/Dockerfile ] && [ -n "$(find ${TASK_FOLDER}/src -name '*.py' -type f)" ]; then
          ls ${TASK_FOLDER}/src
          echo "All files exist inside 'src' "
          else
          echo "Error: Files does not exist inside 'src' "
          exit 1
          fi

      - name: Check if manifests directory has pod.yml file
        run: |
          if [ -f ${TASK_FOLDER}/manifests/pod.yml ]; then
          ls ${TASK_FOLDER}/manifests
          echo "All files exist inside 'manifests' "
          else
          echo "Error: Files does not exist inside 'manifests' "
          exit 1
          fi

      - name: Create cluster
        run: |
          k3d cluster create demo-cluster --registry-create demo-registry:12345 

      - name: Build, tag and push the image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.TASK_FOLDER }}/src
          file: ${{ env.TASK_FOLDER }}/src/Dockerfile
          push: true
          tags: ${{ env.CUSTOM_IMAGE }}

      - name: Check if tagged image was created successfully
        run: |
          TAGGED_IMAGE=$(docker images -q ${{ env.CUSTOM_IMAGE }})
          if [ -n "$TAGGED_IMAGE" ]; then
          echo "Image ${{ env.CUSTOM_IMAGE }} exists"
          else
          echo "Image ${{ env.CUSTOM_IMAGE }} does not exist"
          exit 1
          fi

      - name: Apply manifest
        run: |
          kubectl apply -f ${TASK_FOLDER}/manifests
          kubectl wait pod ${{ env.POD_CONTAINER_NAME }} --for=condition=Ready --timeout=30s
          POD_STATUS=$(kubectl get pod ${{ env.POD_CONTAINER_NAME }} -o jsonpath='{.status.phase}')
          echo "POD_STATUS=${POD_STATUS}" >> $GITHUB_ENV

      - name: Verify pod status
        run: |
          echo "Pod status: $POD_STATUS"
          if [ "${{ env.POD_STATUS }}" == "${{ env.CHECK_POD_STATUS }}" ]; then
          echo "Pod is running successfully"
          else
          echo "Error: Pod is not running"
          exit 1
          fi
          
      - name: Check if Pod logs present
        run: |
          OUTPUT=$(kubectl logs 02-hello-world-python -c ${{ env.POD_CONTAINER_NAME }})
          echo "OUTPUT=${OUTPUT}" >> $GITHUB_ENV
          echo "OUTPUT=${OUTPUT}"
          
      - name: Verify output. Expected output - "Hello, Anna"
        run: |
          if [[ "${{ env.OUTPUT }}" == "${{ env.POD_OUTPUT }}" ]]; then
          echo "Log output contains 'Hello, Anna'"
          else
          echo "Error: Log output does not contain 'Hello, Anna'"
          exit 1
          fi

      - name: Check if pod did not restart
        run: |
          REASTARTS=$(kubectl describe pod 02-hello-world-python | grep -i 'restart count' | grep -o -E '[0-9]{0,2}' | awk '{s+=$1} END {print s}')
          echo "Restart count: $REASTARTS"
          if [ "$REASTARTS" -gt 0 ]; then
          echo "Error: Pod restarted $REASTARTS times."
          exit 1
          fi

    
