name: K-04 Deployment with 4 Pods

on:
  push:
    paths:
      - 'kubernetes/04-deployment-with-4-pods/**'
      - '.github/workflows/04-deployment-with-4-pods.yml'
env:
  IP_COUNT: "4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1

      - name: Print current path
        run: |
          echo ${{ github.workspace }} 

      - name: Check working directory
        run: |
          if [ -d "${{ github.workspace }}/kubernetes/04-deployment-with-4-pods" ]; then
          echo "Directory exists"
          else
          echo "Directory does not exist"
          exit 1
          fi

      - name: Verify Docker installation
        run: docker version

      - name: Verify Kubernetes installation
        run: k3d --version

      - name: Create cluster with registry
        run: k3d cluster create demo-cluster --registry-create demo-registry:12345

      - name: Apply the service manifest
        run: kubectl apply -f ./kubernetes/04-deployment-with-4-pods/manifests/service.yml

      - name: Apply the deployment manifest
        run: kubectl apply -f ./kubernetes/04-deployment-with-4-pods/manifests/deployment.yml

      - name: Wait for pods to be ready
        run: ./check_exit_code.sh 'kubectl wait $(kubectl get pods -n default -l app=04-deployment-with-4-pods -o name) -n default --for=condition=Ready'

      - name: Add port to cluster
        run: k3d cluster edit demo-cluster --port-add 12378:4590@loadbalancer

      - name: Test load balancing
        run: |
          server_addresses=()
          for i in {1..20}; do
          address_value=$(curl -s http://localhost:12378 | grep -E -o "([0-9]{1,3}\.){1,3}[[:digit:]]{1,3}")
          if [[ -n "$address_value" ]] && ! [[ ${server_addresses[@]} =~ $address_value ]]; then
          server_addresses+=("$address_value")
          fi
          sleep 1
          done
          
          echo "Unique address values:"
          for ip_value in "${server_addresses[@]}"; do
          echo "$ip_value"
          done
          
          ip_count=${#server_addresses[@]}
          echo "Number of unique address values: $ip_count"
          echo "ip_count=${ip_count}" >> $GITHUB_ENV

      - name: Check ip addresses count values. Expected count- "4"
        run: |
          if [[ "${{ env.ip_count }}" == "${{ env.IP_COUNT }}" ]]; then
          echo "Load balancing is shared  between 4 pods. Count of pods: $ip_count"
          else
          echo "Error: Load balancing is not shared between 4 pods"
          exit 1
          fi
