name: K-05 Interconnection via Volume

on:
  push:
    paths:
      - 'kubernetes/05-interconnect-two-containers-via-volumes-in-k3d/**'
      - '.github/workflows/05-interconnect-two-containers-via-volumes-in-k3d.yml'

env:
  EXPECTED_OUTPUT: "Hello World"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup k3d
        uses: rinx/setup-k3d@v0.0.3

      - name: Print current path
        run: |
          echo ${{ github.workspace }} 

      - name: Check working directory
        run: |
          if [ -d "${{ github.workspace }}/kubernetes/05-interconnect-two-containers-via-volumes-in-k3d" ]; then
          echo "Directory exists"
          else
          echo "Directory does not exist"
          exit 1
          fi

      - name: Verify Docker installation
        run: docker version

      - name: Verify Kubernetes installation
        run: k3d --version

      - name: Create cluster with registry
        run: k3d cluster create demo-cluster --registry-create demo-registry:12345

      - name: Apply the manifest
        run: kubectl apply -f ./kubernetes/05-interconnect-two-containers-via-volumes-in-k3d/manifests

      - name: Check "reader" container logs
        run: |
          POD_NAME="05-writer-reader"
          kubectl wait pod $POD_NAME --for=condition=Ready --timeout=30s
          OUTPUT=$(kubectl logs 05-writer-reader -c reader-container --follow)
          echo "OUTPUT=${OUTPUT}" >> $GITHUB_ENV
          echo "OUTPUT=${OUTPUT}"

      - name: Compare the output with the expected one
        run: |
          if [[ "${{ env.OUTPUT }}" == "${{ env.EXPECTED_OUTPUT }}" ]]; then
          echo "The outputs match: $OUTPUT, $EXPECTED_OUTPUT "
          else
          echo "The outputs don't match"
          exit 1
          fi
