name: K-07 Dind client and server in k3d

on:
  push:
    paths:
      - 'kubernetes/07-docker-client-and-docker-server-in-k3d/**'
      - '.github/workflows/07-docker-client-and-docker-server-in-k3d.yml'

env:
  PORT: "14999"
  MANIFESTS_FOLDER: "${{ github.workspace }}/kubernetes/07-docker-client-and-docker-server-in-k3d/manifests"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1

      - name: Verify Docker installation
        run: docker version

      - name: Verify Kubernetes installation
        run: k3d --version

      - name: Create cluster with registry
        run: k3d cluster create demo-cluster --registry-create demo-registry:12345

      - name: Apply the service manifest
        run: kubectl apply -f ${{ env.MANIFESTS_FOLDER }}/service.yml

      - name: Apply the deployment manifest
        run: kubectl apply -f ${{ env.MANIFESTS_FOLDER }}/deployment.yml

      - name: Wait for pods to be ready
        run: ./wait_status_code_and_logs.sh 'kubectl wait deployment -n default 07-client-and-server --for=condition=Available'

      - name: Add port to cluster
        run: k3d cluster edit demo-cluster --port-add ${{ env.PORT }}:8092@loadbalancer

      - name: Check curl
        run: |
          ./wait_status_code_and_logs.sh 'curl -i http://localhost:${{ env.PORT }}'
          curl -i http://localhost:${{ env.PORT }}  

      - name: Check site for status code
        uses: pavelsaman/website-check@v2.3
        with:
          url: http://localhost:${{ env.PORT }}
          status_code: 200
          redirect: true