name: K-08 Java Testcontainers in k3d
on:
  push:
    paths:
      - '.github/workflows/08-java-testcontainers-in-k3d.yml'
      - 'kubernetes/08-java-testcontainers-in-k3d/**'
env:
  USER_ID: "$(id -u)"
  GROUP_ID: "$(id -g)"
  CHECK_BUILD_OUTPUT: "BUILD SUCCESSFUL"
  WORK_PATH: "${{ github.workspace }}/kubernetes/08-java-testcontainers-in-k3d"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1

      - name: Verify Docker installation
        run: docker version

      - name: Verify Kubernetes installation
        run: k3d --version

      - name: Initialize and update submodule
        run: |
          git submodule update --init --recursive submodules/testcontainers-java
          cp -r ./submodules/testcontainers-java ${WORK_PATH}/src
          if [ -d ${WORK_PATH}/src/testcontainers-java ]; then
          echo "Submodule directory exists"
          else
          echo "Submodule directory does not exist"
          exit 1
          fi

      - name: Create report folder and check if it was successfully created
        run: |
          mkdir ${WORK_PATH}/report
          if [ -d ${WORK_PATH}/report ]; then
          echo "Report folder was created"
          ls ${WORK_PATH}/report   
          else
          echo "Report folder wasn't created"
          exit 1
          fi

      - name: Create cluster with registry
        run: |
          k3d cluster create demo-cluster \
          --registry-create demo-registry:12345 \
          --volume ${WORK_PATH}/report:/report

      - name: Build, tag and push the image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.WORK_PATH }}/src
          file: ${{ env.WORK_PATH }}/src/Dockerfile
          push: true
          tags: localhost:12345/08-java-testcontainers-in-k3d:0.1
          build-args: |
            USER_ID=$(id -u)
            GROUP_ID=$(id -g)

      - name: Apply manifest
        run: |
          kubectl apply -f ${WORK_PATH}/manifests

      - name: Watch `testcontainer` container logs
        run: |
          ./wait_status_code_and_logs.sh 'kubectl logs 08-java-testcontainers -c testcontainer' 'BUILD SUCCESSFUL'
          kubectl logs 08-java-testcontainers -c testcontainer > 08-task-logs.txt
          BUILD_OUTPUT=$(grep "BUILD SUCCESSFUL" 08-task-logs.txt)
          echo "BUILD_OUTPUT=${BUILD_OUTPUT}" >> $GITHUB_ENV

      - name: Check "testcontainer" container output. Extract build output and check if output is "BUILD SUCCESSFUL"
        run: |
          if [[ "${{ env.BUILD_OUTPUT }}" == *"${{ env.CHECK_BUILD_OUTPUT }}"* ]]; then
          echo "The build is successful"
          else
          echo "The build is failed"
          exit 1
          fi

      - name: Check if report is available in the report folder an report file exists
        run: |
          if [ -f ${WORK_PATH}/report/java/reports/tests/test/index.html ]; then
          echo "Report exists"
          cat ${WORK_PATH}/report/java/reports/tests/test/index.html
          else
          echo "Report does not exists"
          exit 1
          fi

      - name: Check report folder rights
        run: |
          USER=$(stat -c '%U' ${WORK_PATH}/report)
          GROUP=$(stat -c '%G' ${WORK_PATH}/report)
          if [[ "$USER" == "$(id -un)" && "$GROUP" == "$(id -gn)" ]]; then
          echo "User=$USER, $(id -un)"
          echo "Group=$GROUP, $(id -gn)" 
          else
          echo "Error: user and group are incorrect"
          exit 1
          fi 
