name: D-09 Node Testcontainers
on:
  push:
    paths:
      - './docker/09-node-testcontainers/**'
      - '.github/workflows/09-node-testcontainers.yml'

env:
  BUILD_ARGUMENT_USER_ID: "$(id -u)"
  BUILD_ARGUMENT_GROUP_ID: "$(id -g)"
  BUILD_IMAGE: "09-node-testcontainers:0.1"
  DIND_CONTAINER_STATUS: "running"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Print current path
        run: |
          echo ${{ github.workspace }}

      - name: Check if directory
        working-directory: ${{ github.workspace }}/docker/09-node-testcontainers
        run: |
          if [ -d "${{ github.workspace }}/docker/09-node-testcontainers" ]; then
          echo "Directory exists"
          else
          echo "Directory does not exist"
          exit 1
          fi    

      - name: Check docker available
        run: docker info

      - name: Initialize and update submodule
        run: |
          git submodule update --init --recursive submodules/testcontainers-node
          cp -r ./submodules/testcontainers-node ./docker/09-node-testcontainers/src/
          if [ -d "./docker/09-node-testcontainers/src/testcontainers-node" ]; then
          echo "Submodule directory exists"
          else
          echo "Submodule directory does not exist"
          exit 1
          fi

      - name: Create network. Check if network was created successfully.
        run: |
          docker network create demo-network
          docker network ls | grep demo-network
          if [ $? -eq 0 ]; then
          echo " "demo-network" network was created"
          fi

      - name: Run dind container. Check if dind container was created successfully.
        run: |
          docker run --privileged -d -p 12383:2375 --name dind -e DOCKER_TLS_CERTDIR="" --network demo-network docker:23.0.1-dind
          sleep 10
          docker ps -a
          docker ps -a | grep dind
          if [ $? -eq 0 ]; then
          echo "Dind container was created"
          fi
          STATUS=$(docker inspect -f '{{ .State.Status }}' dind )
          echo "DIND_STATUS=${STATUS}" >> $GITHUB_ENV

      - name:  Check dind container status
        run: |
          if [[ "${{ env.DIND_STATUS }}" != "${{ env.DIND_CONTAINER_STATUS }}" ]]; then
          echo "Containers did not exit successfully"
          exit 1
          fi
          echo "Dind container is running"

      - name: Build Docker image. Check if image was created successfully.
        run: |
          docker build -t 09-node-testcontainers:0.1 --build-arg USER_ID=${{ env.BUILD_ARGUMENT_USER_ID }}  \
          --build-arg GROUP_ID=${{ env.BUILD_ARGUMENT_GROUP_ID }} \
          ./docker/09-node-testcontainers/src/
          sleep 10
          docker images
          docker images | grep 09-node-testcontainers
          if [ $? -eq 0 ]; then
          echo "Image was created"
          fi 

      - name: Build Docker image. Check if image was created successfully.
        run: |
          docker build -t 09-node-testcontainers:0.1 ./docker/09-node-testcontainers/src/
          sleep 10
          docker images
          docker images | grep 09-node-testcontainers
          if [ $? -eq 0 ]; then
          echo "Image was created"
          fi

      - name: Create report folder. Check if report folder was created successfully.
        run: |
          mkdir ./docker/09-node-testcontainers/report
          if [ -d "${{ github.workspace }}/docker/09-node-testcontainers/report" ]; then
          echo "Report folder exist"
          else
          echo "Report folder does not exist"
          exit 1
          fi

      - name: Run "testcontainer-node" container
        run: |
          docker run --name testcontainer-node --rm \
          --mount type=bind,source=${{ github.workspace }}/docker/09-node-testcontainers/report,target=/app/report \
          --network demo-network  09-node-testcontainers:0.1

      - name: Check if report is available in the report folder
        run: |
          cd ${{ github.workspace }}/docker/09-node-testcontainers/report/node
          ls -lha
          if [ -f "${{ github.workspace }}/docker/09-node-testcontainers/report/node/index.html" ]; then
          echo "Report exist"
          cat ${{ github.workspace }}/docker/09-node-testcontainers/report/node/index.html
          else
          echo "Report does not exist"
          exit 1
          fi

      - name: Check build status. Check if number of passed tests equal 4
        run: |
          PASSED=$(grep -oP '(?<=<div class="summary-total">Tests \(4\)</div><div class="summary-passed ">)[0-9]+(?= passed</div>)' /home/runner/work/training-devops-aiudina/training-devops-aiudina/docker/09-node-testcontainers/report/node/index.html)
          echo "Tests Passed: $PASSED"
          if [ "$PASSED" -eq 4 ]; then
            echo "There are 4 passed tests"
          else
          echo "Error. Tests do not match the expected results. Number of passed test=$PASSED"
          exit 1
          fi

      - name: Check report folder rights
        run: |
          folder_path="${{ github.workspace }}/docker/09-node-testcontainers/report/node"
          user=$(stat -c '%U' $folder_path)
          group=$(stat -c '%G' $folder_path)
          if [[ "$user" == "$(id -un)" && "$group" == "$(id -gn)" ]]; then
          echo "User=$user, $(id -un)"
          echo "Group=$group, $(id -gn)" 
          else
          echo "Error: user and group are incorrect"
          exit 1
          fi 
